services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD: posPassword1
      - POSTGRES_USER: postgres
      - POSTGRES_DB: demodb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
